// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxG1saGdEH5PrhXx52vIxjjidDOf-NajQ',
    appId: '1:545162892841:web:b9f51eeb5934452dd2ee38',
    messagingSenderId: '545162892841',
    projectId: 'ecomm-prj-sachin',
    authDomain: 'ecomm-prj-sachin.firebaseapp.com',
    storageBucket: 'ecomm-prj-sachin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4SNHRfQsxjiNyTrTwqxZkPgRPOEo8GFE',
    appId: '1:545162892841:android:8a5e73f4ce6b1bbed2ee38',
    messagingSenderId: '545162892841',
    projectId: 'ecomm-prj-sachin',
    storageBucket: 'ecomm-prj-sachin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDD1cymuffL_Ky4lhH3ax4tiV9Uswy6Ao',
    appId: '1:545162892841:ios:b9172a39d14b9756d2ee38',
    messagingSenderId: '545162892841',
    projectId: 'ecomm-prj-sachin',
    storageBucket: 'ecomm-prj-sachin.appspot.com',
    iosClientId: '545162892841-n4lm3er8m44ngk5102m9dvpbs98tpmo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.vedantapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDD1cymuffL_Ky4lhH3ax4tiV9Uswy6Ao',
    appId: '1:545162892841:ios:b9172a39d14b9756d2ee38',
    messagingSenderId: '545162892841',
    projectId: 'ecomm-prj-sachin',
    storageBucket: 'ecomm-prj-sachin.appspot.com',
    iosClientId: '545162892841-n4lm3er8m44ngk5102m9dvpbs98tpmo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.vedantapp',
  );
}
